apiVersion: v1
kind: Service
metadata:
  name: pedidos-service
  labels:
    app: pedidos
spec:
  selector:
    app: pedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  # No cluster real, podemos usar ClusterIP. O Ingress (Gateway) expõe para fora.
  type: ClusterIP
