name: CI/CD Pipeline - Loja Veloz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./pedidos
      run: npm install

    - name: Build Docker Image (Validação)
      working-directory: ./pedidos
      run: docker build -t loja-veloz-pedidos:latest .

  deploy-to-k8s:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to K8s via Kubectl (Mock)
      run: |
        echo "Autenticando no cluster..."
        echo "kubectl apply -f k8s/"
        echo "Deploy Rolling Update finalizado!"
